config/routes.rb
Dakshina::Application.routes.draw do
  resources :learning_paths

  get 'welcome/index'

  resources :capsules

  get 'learning_paths/:id/potential_capsules' => 'learning_elements#potential_capsules_for_path', as: :potential_capsules
  post 'learning_paths/:id/add_capsules' => 'learning_elements#add_capsules_to_path', as: :add_capsules_to_path
  delete 'learning_paths/:id/remove_capsule/:capsule_id' => 'learning_elements#remove_capsule_from_path', as: :remove_capsule_from_path

  root 'welcome#index'

end

app/models/capsule.rb
class Capsule < ActiveRecord::Base

  validates :title, length: { minimum: 3 }, uniqueness: true
  validates :description, length: { minimum: 5 }

  has_many :learning_path_elements
  has_many :learning_paths, :through => :learning_path_elements

end

app/models/learning_path.rb
class LearningPath < ActiveRecord::Base
  validates :name, length: { minimum: 2 }, uniqueness: true

  has_many :learning_path_elements, ->{order (:position)}
  has_many :capsules, :through => :learning_path_elements

end

app/models/learning_path_element.rb
class LearningPathElement < ActiveRecord::Base
  belongs_to :learning_path
  belongs_to :capsule

  validates_uniqueness_of :position, :scope => [:learning_path]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/capsules_controller.rb
class CapsulesController < ApplicationController
  def new
    @capsule = Capsule.new
  end

  def create
    @capsule = Capsule.new(capsule_params)

    if @capsule.save
      redirect_to @capsule
    else
      render 'new'
    end


  end


  def show
    @capsule = Capsule.find(params[:id])
  end


  def index
    @capsules = Capsule.all
  end


  def edit
    @capsule = Capsule.find(params[:id])
  end

  def update
    @capsule = Capsule.find(params[:id])

    if @capsule.update(capsule_params)
      redirect_to @capsule
    else
      render 'edit'
    end
  end


  def destroy
    @capsule = Capsule.find(params[:id])

    path_count = learning_paths_that_map_on_capsule @capsule.id

    if (path_count>0)
      redirect_to capsules_path, alert: "Cannot delete capsule #{@capsule.title} since it is being used in #{path_count} learning paths."
      return
    else
      @capsule.destroy
      redirect_to capsules_path, notice: 'Capsule deleted: '+ @capsule.title
    end

  end

  private
    def capsule_params
      params.require(:capsule).permit(:title, :description, :study_text, :assignment_instructions, :guidelines_for_evaluators)
    end

    def learning_paths_that_map_on_capsule(capsule_id)
      LearningPathElement.where(:capsule_id => capsule_id).count
    end


end

app/controllers/learning_elements_controller.rb
class LearningElementsController < ApplicationController

  before_action :get_learning_path

  def potential_capsules_for_path

    if @learning_path.capsules.count > 0
      @potential_capsules = Capsule.where('id not in (?)', @learning_path.capsules.map(&:id))
    else
      puts 'Returning all capsules'
      @potential_capsules = Capsule.all
      puts ("Number of capsules returned: #{@potential_capsules.size}")
    end

    # Don't render layout when request is AJAX
    render :layout => !request.xhr?
  end


  def add_capsules_to_path
    redirect_to @learning_path, alert: 'No updates were made to the path!' and return if (params[:learning_path].nil?)

    position = @learning_path.capsules.size + 1
    selected_capsules = Capsule.find params[:learning_path][:capsule_ids]

    selected_capsules.each{ |capsule|
      @learning_path.learning_path_elements.build(:capsule_id => capsule.id, :position => position)
      position = position + 1
    }

    if(@learning_path.save)
      redirect_to @learning_path, notice: 'Learning path was successfully updated.'
    else
      redirect_to @learning_path, alert: 'Learning path could not be updated!'
    end

  end


  def remove_capsule_from_path
    capsule_id_to_remove = params[:capsule_id].to_s
    position = -1
    deleted_successfully = false
    @learning_path.learning_path_elements.each { |element|
      if (element.capsule_id.equal? capsule_id_to_remove.to_i)
        position = element.position
        if element.destroy
          deleted_successfully = true
        end
      end
    }

    redirect_to @learning_path, alert: 'No updates were made to the path! Delete failed' and return unless deleted_successfully

    @learning_path.reload

    update_positions_for_remaining_capsules(position)

    redirect_to @learning_path, notice: 'Capsule removed from path!'
  end


  private

      def get_learning_path
        @learning_path = LearningPath.find(params[:id])
      end

      def update_positions_for_remaining_capsules(position)
        @learning_path.learning_path_elements.each { |element|
          current_position = element.position
          if current_position > position
            element.position = position
            position = position + 1
            element.save!
          end
        }
      end


end

app/controllers/learning_paths_controller.rb
class LearningPathsController < ApplicationController
  before_action :set_learning_path, only: [:show, :edit, :update, :destroy]

  # GET /learning_paths
  def index
    @learning_paths = LearningPath.all
  end

  # GET /learning_paths/1
  def show
  end

  # GET /learning_paths/new
  def new
    @learning_path = LearningPath.new
  end

  # GET /learning_paths/1/edit
  def edit
  end

  # POST /learning_paths
  def create
    @learning_path = LearningPath.new(learning_path_params)

    if @learning_path.save
      redirect_to @learning_path, notice: 'Learning path was successfully created.'
    else
      render action: 'new'
    end

  end

  # PATCH/PUT /learning_paths/1
  def update
    if @learning_path.update(learning_path_params)
      redirect_to @learning_path, notice: 'Learning path was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /learning_paths/1
  def destroy
    @learning_path.destroy
    redirect_to learning_paths_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_learning_path
      @learning_path = LearningPath.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def learning_path_params
      params.require(:learning_path).permit(:name, :description, :objective)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/capsules_helper.rb
module CapsulesHelper
end

app/helpers/learning_paths_helper.rb
module LearningPathsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/capsules/_form.html.slim
= render 'common/errorMessage', passedErrors: @capsule.errors
= simple_form_for @capsule, defaults: { input_html: { class: 'form-control' } } do |f|
  .panel-group
    .panel.panel-primary
      .panel-heading
        h3.panel-title Capsule Details
      .panel-body
          = f.input :title
          br
          = f.input :description
    .panel.panel-success
      .panel-heading
        h3.panel-title Study Material
      .panel-body
        = f.input :study_text, label: false, input_html: {rows: '10'}
    .panel.panel-success
      .panel-heading
        h3.panel-title Assignment for Student
      .panel-body
        = f.input :assignment_instructions, label: false
    .panel.panel-success
      .panel-heading
        h3.panel-title Guidelines for Evaluators
      .panel-body
        = f.input :guidelines_for_evaluators, label: false

  p
  div.btn-toolbar align='left'
    = link_to '< Back', @capsule, :class=> 'btn btn-primary btn-sm'
    = f.submit 'Save Capsule', :class => 'btn btn-warning btn-sm'

app/views/capsules/_form.slim
= render 'common/errorMessage', passedErrors: @capsule.errors
= simple_form_for @capsule, defaults: { input_html: { class: 'form-control' } } do |f|
  .panel-group
    .panel.panel-primary
      .panel-heading
        h3.panel-title Capsule Details
      .panel-body
          = f.input :title
          br
          = f.input :description
    .panel.panel-success
      .panel-heading
        h3.panel-title Study Material
      .panel-body
        = f.input :study_text, label: false, input_html: {rows: '10'}
    .panel.panel-success
      .panel-heading
        h3.panel-title Assignment for Student
      .panel-body
        = f.input :assignment_instructions, label: false
    .panel.panel-success
      .panel-heading
        h3.panel-title Guidelines for Evaluators
      .panel-body
        = f.input :guidelines_for_evaluators, label: false

  p
  div.btn-toolbar align="left"
    = link_to '< Back', @capsule, :class=> "btn btn-primary"
    = f.submit 'Save Capsule', :class => 'btn btn-warning'

app/views/capsules/edit.html.slim
.page-header
    h1 = @capsule.title

= render 'form'

app/views/capsules/edit.slim
.page-header
    h1 = @capsule.title

= render 'form'

app/views/capsules/index.html.slim
.page-header
  h1 Capsules

= render 'common/flashMessage'

.panel.panel-success
  .panel-heading
    h3.panel-title List of Learning Capsules
  .panel-body
    p
      i
        | The following capsules are currently defined in Dakshina. A Capsule represents the smallest learning unit in Dakshina
        | which a student can complete. A Capsule has Study material, Assignment Details and Evaluator Instructions associated
        | with it. You can then define Tracks (or Learning Paths) by choosing appropriate Capsules.
    table.table.table-hover
      tr
        th Title
        th Description
        th
      - @capsules.each do |capsule|
        tr
          td
            =' image_tag 'capsule.ico'
            = capsule.title
          td = capsule.description
          td
            .btn-toolbar
              = link_to 'Show Details', capsule, :class=> "btn btn-primary btn-xs"
              = link_to 'Edit', edit_capsule_path(capsule) , :class=> "btn btn-warning btn-xs"
              = link_to 'Delete', capsule_path(capsule),  method: :delete, data: { confirm: 'DELETE the capsule?' }, :class=> "btn btn-danger btn-xs"

div.btn-toolbar align="center"
  = link_to "< Home", welcome_index_path, :class=> "btn btn-primary btn-sm"
  = link_to "+ New Capsule", new_capsule_path, :class=> "btn btn-primary btn-sm"

app/views/capsules/index.slim
.page-header
  h1 Capsules
.panel.panel-success
  .panel-heading
    h3.panel-title List of Learning Capsules
  .panel-body
    p
      i
        | The following capsules are currently defined in Dakshina. A Capsule represents the smallest learning unit in Dakshina
        | which a student can complete. A Capsule has Study material, Assignment Details and Evaluator Instructions associated
        | with it. You can then define Tracks (or Learning Paths) by choosing appropriate Capsules.
    table.table.table-hover
      tr
        th Title
        th Description
        th
      - @capsules.each do |capsule|
        tr
          td
            =' image_tag 'capsule.ico'
            = capsule.title
          td = capsule.description
          td
            .btn-toolbar
              = link_to 'Show Details', capsule, :class=> "btn btn-primary"
              = link_to 'Edit', edit_capsule_path(capsule) , :class=> "btn btn-warning"
              = link_to 'Delete', capsule_path(capsule),  method: :delete, data: { confirm: 'Are you sure?' }, :class=> "btn btn-danger"

div.btn-toolbar align="center"
  = link_to "< Home", welcome_index_path, :class=> "btn btn-primary"
  = link_to "+ New Capsule", new_capsule_path, :class=> "btn btn-primary"

app/views/capsules/new.html.slim
.page-header
  h1 New Learning Capsule

= render 'form'

app/views/capsules/new.slim
.page-header
  h1 New Learning Capsule

= render 'form'

app/views/capsules/show.html.slim
.page-header
  h1 id='capsule-title-page'
    = @capsule.title
    br
    small = @capsule.description


= render :partial => '/common/box', :locals => { :title => 'Study Material', :body => simple_format(@capsule.study_text)}

= render :partial => '/common/box', :locals => { :title => 'Assignment for Student', :body => simple_format(@capsule.assignment_instructions)}

= render :partial => '/common/box', :locals => { :title => 'Guidelines for Evaluators', :body => simple_format(@capsule.guidelines_for_evaluators)}



div.btn-toolbar align='left'
  = link_to '< Back', capsules_path, :class=> 'btn btn-primary btn-sm'
  = link_to 'Edit', edit_capsule_path(@capsule), :class=> 'btn btn-warning btn-sm'

app/views/capsules/show.slim
.page-header
  h1 id="capsule-title-page"
    = @capsule.title
    br
    small = @capsule.description


= render :partial => '/common/box', :locals => { :title => 'Study Material', :body => simple_format(@capsule.study_text)}

= render :partial => '/common/box', :locals => { :title => 'Assignment for Student', :body => simple_format(@capsule.assignment_instructions)}

= render :partial => '/common/box', :locals => { :title => 'Guidelines for Evaluators', :body => simple_format(@capsule.guidelines_for_evaluators)}



div.btn-toolbar align="left"
  = link_to "< Back", capsules_path, :class=> "btn btn-primary"
  = link_to "Edit", edit_capsule_path(@capsule), :class=> "btn btn-warning"

app/views/common/_bootstrap_modal.html.slim
/! Modal
#bootstrapModal.modal.fade aria-hidden='true' aria-labelledby='bootstrapModalLabel' role='dialog' tabindex='-1'
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-hidden='true' data-dismiss='modal' type='button'
        h4.modal-title id='bootstrapModalLabel'
          |SOME TITLE
      .modal-body
        | SOME BODY
      .modal-footer
        button.btn.btn-default data-dismiss='modal' type='button'
          | Close
        button.btn.btn-primary type='button' id='saveButtonOnModal'
          | Save

app/views/common/_box.html.slim
.panel.panel-success
  .panel-heading
    h3.panel-title
      = title
  .panel-body
    = body

app/views/common/_box.slim
.panel.panel-success
  .panel-heading
    h3.panel-title
      = title
  .panel-body
    = body

app/views/common/_errorMessage.html.slim
- if passedErrors.any?
  .alert.alert-danger.alert-dismissable
    button.close aria-hidden="true" data-dismiss="alert" type="button"
    strong Error!
    p
      = pluralize(passedErrors.count, "error")
      |  prohibited this form from being saved:
      ul
        - passedErrors.full_messages.each do |msg|
          li = msg

app/views/common/_errorMessage.slim
- if passedErrors.any?
  .alert.alert-danger.alert-dismissable
    button.close aria-hidden="true" data-dismiss="alert" type="button"
    strong Error!
    p
      = pluralize(passedErrors.count, "error")
      |  prohibited this form from being saved:
      ul
        - passedErrors.full_messages.each do |msg|
          li = msg

app/views/common/_flashMessage.html.slim
- if notice
  .alert.alert-success.alert-dismissable
    button.close type='button' data-dismiss='alert'
      |x
    em
      = notice

- if alert
  .alert.alert-warning.alert-dismissable
    button.close type='button' data-dismiss='alert'
      |x
    em
      = alert

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dakshina</title>
  <link href="/images/favicon.ico?v=1" rel="icon" type="image/x-icon" />
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <%= link_to "Dakshina", welcome_index_path, :class=>"navbar-brand" %>
  </div>


  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><a href="#">Link</a></li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <li><a href="#">
        <span class="glyphicon glyphicon-flash"></span>
        Admin
      </a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <span class="glyphicon glyphicon-user"></span>
          Gurpreet
          <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li class="divider"></li>
          <li><a href="#"> <span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
        </ul>
      </li>
    </ul>
  </div>
</nav>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/learning_elements/potential_capsules_for_path.html.slim
= form_for @learning_path, :url => add_capsules_to_path_path, :method => :post do
  .panel.panel-primary
    .panel-heading
      h3.panel-title Choose capsules to add to learning path
    .panel-body
      table.table.table-hover
        tr
          th Select
          th Title
          th Time (hours)
        - @potential_capsules.each do |c|
          tr
            td
              = check_box_tag :capsule_ids, c.id, false, :name => 'learning_path[capsule_ids][]'
            td
              =' image_tag 'capsule.ico'
              = c.title
            td
              | 6

app/views/learning_paths/_form.html.slim
= render 'common/errorMessage', passedErrors: @learning_path.errors
= simple_form_for @learning_path, defaults: { input_html: { class: 'form-control' } } do |f|
  .panel-group
    .panel.panel-primary
      .panel-heading
        h3.panel-title Learning Path Details
      .panel-body
          = f.input :name
          br
          = f.input :description
          br
          = f.input :objective

  p
  div.btn-toolbar align="left"
    = link_to '< Back', @learning_path, :class=> 'btn btn-primary btn-sm'
    = f.submit 'Save Learning Path', :class => 'btn btn-warning btn-sm'

app/views/learning_paths/_form.slim
= render 'common/errorMessage', passedErrors: @learning_path.errors
= simple_form_for @learning_path, defaults: { input_html: { class: 'form-control' } } do |f|
  .panel-group
    .panel.panel-primary
      .panel-heading
        h3.panel-title Learning Path Details
      .panel-body
          = f.input :name
          br
          = f.input :description
          br
          = f.input :objective

  p
  div.btn-toolbar align="left"
    = link_to '< Back', @learning_path, :class=> "btn btn-primary"
    = f.submit 'Save Learning Path', :class => 'btn btn-warning'

app/views/learning_paths/edit.html.slim
.page-header
    h1
      =' @learning_path.name
      span.glyphicon.glyphicon-road

= render 'form'

app/views/learning_paths/edit.slim
.page-header
    h1
      =' @learning_path.name
      span.glyphicon.glyphicon-road

= render 'form'

app/views/learning_paths/index.html.slim
.page-header
  h1 Learning Paths

.panel.panel-info
  .panel-heading
    h3.panel-title List of Learning Paths
  .panel-body
    p
      i
        | A Learning Path (or Track) is a series of Capsules which a student needs to undergo to gain reasonable knowledge about a subject.
    table.table.table-hover
      tr
        th
        th Name
        th Description
        th Objective
        th Capsules
        th
      - @learning_paths.each do |learning_path|
        tr
          td
            span.glyphicon.glyphicon-road
          td = learning_path.name
          td = learning_path.description
          td = learning_path.objective
          td = learning_path.capsules.count
          td
            .btn-toolbar
              = link_to 'Show Details', learning_path, :class=> 'btn btn-primary btn-xs'
              = link_to 'Edit', edit_learning_path_path(learning_path) , :class=> 'btn btn-warning btn-xs'
              = link_to 'Delete', learning_path_path(learning_path),  method: :delete, data: { confirm: 'Are you sure?' }, :class=> 'btn btn-danger btn-xs'

div.btn-toolbar align='center'
  = link_to '< Home', welcome_index_path, :class=> 'btn btn-primary btn-sm'
  = link_to '+ New Learning Path', new_learning_path_path, :class=> 'btn btn-primary btn-sm'

app/views/learning_paths/index.slim
.page-header
  h1 Learning Paths

.panel.panel-info
  .panel-heading
    h3.panel-title List of Learning Paths
  .panel-body
    p
      i
        | A Learning Path (or Track) is a series of Capsules which a student needs to undergo to gain reasonable knowledge about a subject.
    table.table.table-hover
      tr
        th
        th Name
        th Description
        th Objective
        th Capsules
        th
      - @learning_paths.each do |learning_path|
        tr
          td
            span.glyphicon.glyphicon-road
          td = learning_path.name
          td = learning_path.description
          td = learning_path.objective
          td = learning_path.capsules.count
          td
            .btn-toolbar
              = link_to 'Show Details', learning_path, :class=> "btn btn-primary"
              = link_to 'Edit', edit_learning_path_path(learning_path) , :class=> "btn btn-warning"
              = link_to 'Delete', learning_path_path(learning_path),  method: :delete, data: { confirm: 'Are you sure?' }, :class=> "btn btn-danger"

div.btn-toolbar align="center"
  = link_to "< Home", welcome_index_path, :class=> "btn btn-primary"
  = link_to "+ New Learning Path", new_learning_path_path, :class=> "btn btn-primary"

app/views/learning_paths/new.html.slim
.page-header
  h1 New Learning Path

= render 'form'

app/views/learning_paths/new.slim
.page-header
  h1 New Learning Path

= render 'form'

app/views/learning_paths/show.html.slim
javascript:
  $(function() {

      // intiliaze the modal but don't show it yet
      $("#bootstrapModal").modal('hide');

      $('a[data-target="#bootstrapModal"]').click(function(event) {
          event.preventDefault();
          var myModal = $('#bootstrapModal');
          modalBody = myModal.find('.modal-body');
          //Set title for modal
          myModal.find('.modal-title').text('#{@learning_path.name}')
          // load content into modal
          myModal.find('.modal-body').load('#{potential_capsules_path(@learning_path)}');
          // display modal
          myModal.modal('show');
      });

     $('#bootstrapModal #saveButtonOnModal').click(function(e) {
            e.preventDefault();
            $('#bootstrapModal').modal('hide');
            $('form').submit();
        });

  });

.page-header
  h1 id='learning-path-view-page'
    =' @learning_path.name
    span.glyphicon.glyphicon-road


= render 'common/flashMessage'

.panel.panel-info
  .panel-heading
    h3.panel-title
      |Details
      div align='right'
        = link_to 'Edit Details', edit_learning_path_path(@learning_path), :class=> 'btn btn-primary btn-xs'

  .panel-body
    = @learning_path.description
    br
    br
    b Objective
    br
    = @learning_path.objective


= render 'common/bootstrap_modal'

.panel.panel-info
  .panel-heading
    h3.panel-title
      |Capsules in this Learning Path
      div align='right'
        div.btn-toolbar
          a.btn.btn-primary.btn-xs href='#javascript will be triggered' data-toggle='modal' data-target='#bootstrapModal'
            |Add Capsules


  .panel-body
      table.table.table-hover
        tr
          th Title
          th Description
          th Approx Time (hours)
          th
        - @learning_path.capsules.each do |c|
          tr
            td
              =' image_tag 'capsule.ico'
              = c.title
            td = c.description
            td 6
            td
              = link_to ' ', remove_capsule_from_path_path(@learning_path, c), method: :delete, data: { confirm: 'Remove the capsule?' }, :class=> 'btn btn-warning btn-xs glyphicon glyphicon-remove'

div.btn-toolbar align='left'
  = link_to '< Back', learning_paths_path, :class=> 'btn btn-primary btn-sm'

app/views/learning_paths/show.slim
.page-header
  h1 id="learning-path-view-page"
    =' @learning_path.name
    span.glyphicon.glyphicon-road

.panel.panel-info
  .panel-heading
    h3.panel-title
      |Details
      div align='right'
        = link_to 'Edit Details', edit_learning_path_path(@learning_path), :class=> 'btn btn-warning'


  .panel-body
    = @learning_path.description
    br
    br
    b Objective
    br
    = @learning_path.objective


.panel.panel-info
  .panel-heading
    h3.panel-title
      |Capsules in this Learning Path
      div align='right'
        = link_to 'Add Capsule', edit_learning_path_path(@learning_path), :class=> 'btn btn-warning'

  .panel-body
      table.table.table-hover
        tr
          th Title
          th Description
          th Approx Time (hours)
        - @learning_path.capsules.each do |c|
          tr
            td
              =' image_tag 'capsule.ico'
              = c.title
            td = c.description
            td 6

div.btn-toolbar align='left'
  = link_to '< Back', learning_paths_path, :class=> 'btn btn-primary'

app/views/welcome/index.html.slim
.jumbotron
    h1
      | Dakshina
    p
      | &nbsp; A Simple Learning Management Solution
    br
    .btn-toolbar
      = link_to 'Capsules', {:controller=> 'capsules'}, :class=> 'btn btn-primary'
      = link_to 'Learning Paths', {:controller=> 'learning_paths'}, :class=> 'btn btn-primary'

app/views/welcome/index.slim
.jumbotron
    h1 Dakshina
    p
      span.glyphicon.glyphicon-gift
      | &nbsp; Welcome to Dakshina. Choose an option below.
    br
    .btn-toolbar
      = link_to "Learning Paths", {:controller=> "learning_paths"}, :class=> "btn btn-primary btn-lg"
      = link_to "Capsules", {:controller=> "capsules"}, :class=> "btn btn-primary btn-lg"